apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: bestplacestours-co-uk-tls
spec:
  secretName: bestplacestours-co-uk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: bestplacestours.co.uk
  dnsNames:
    - bestplacestours.co.uk
    - www.bestplacestours.co.uk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - bestplacestours.co.uk
          - www.bestplacestours.co.uk
